---
title: "Factor n Cluster Analysis"
output: html_document
---

```{r}
library(dplyr)
library(foreign)
library(cluster)
library(REdaS)
library(psych)
```

```{r}
superdata <- read.csv("./data/SUPERMARKET300.csv")
superdata_cri <- superdata[,9:20]
```

##################### FACTOR ANALYSIS ##################### 

KMOS TEST

```{r}
KMOS(superdata_cri, use ="complete.obs")
# all MSA  >0.5 = cukup untuk dipakai

```


-----------------------------------------------------
BARTLETT TEST OF SPHERICITY

```{r}
bart_spher(superdata_cri, use="complete.obs")
# p value <0.05 = variabel bisa digunakan di analisis factor
```

-----------------------------------------------------
PRINCIPAL COMPONENT ANALYSIS

```{r}
super <- princomp(na.omit(superdata_cri), cor = T)
plot(super, type="lines") 
# jadi kita akan punya 4 komponen

summary(super)
```

-----------------------------------------------------

```{r}
componen <- principal(na.omit(superdata_cri), nfactors = 4, rotate = "varimax")
# nfactors = 4 (berdasarkan factor analysis tadi?)

componen

print(componen$loadings, cutoff = 0.5)

```

##################### CLUSRTER ANALYSIS ##################### 


```{r}
klusterModel <- kmeans(superdata_cri, 4, iter.max = 25)
summary(klusterModel)

#Puter matrix
t(klusterModel$centers)

```

```{r}
clusplot(superdata_cri, klusterModel$cluster, main='Clusters of Supermarket Customers',
         color=T, shade=F,
         labels=2,
         lines=0)

o=order(klusterModel$cluster)
nama <- data.frame(superdata$custID[o], klusterModel$cluster[o])

nama

table(nama$klusterModel.cluster.o.)
```

##################### SORT N COMBINE ####################

```{r}
superdata <- superdata[order(superdata$custID),]
nama_sort <- nama[order(nama$superdata.custID.o.),]
superdata_new <- cbind(superdata, nama_sort)

head(superdata_new)
```


